apiVersion: storage.halo.run/v1alpha1
kind: PolicyTemplate
metadata:
  name: s3os
spec:
  displayName: S3 Object Storage
  settingName: s3os-policy-template-setting
---
apiVersion: v1alpha1
kind: Setting
metadata:
  name: s3os-policy-template-setting
spec:
  forms:
    - group: default
      formSchema:
        - $formkit: text
          name: bucket
          label: Bucket 桶名称
          validation: required
        - $formkit: select
          name: endpointProtocol
          label: Endpoint 访问协议
          options:
            - label: HTTPS
              value: https
            - label: HTTP
              value: http
          validation: required
        - $formkit: select
          name: enablePathStyleAccess
          label: Endpoint 访问风格
          options:
            - label: Virtual Hosted Style
              value: false
            - label: Path Style
              value: true
          value: false
          validation: required
        - $formkit: text
          name: endpoint
          label: EndPoint
          validation: required
          help: 协议头请在上方设置，此处无需以"http://"或"https://"开头，系统会自动拼接
        - $formkit: password
          name: accessKey
          label: Access Key
          validation: required
        - $formkit: password
          name: accessSecret
          label: Access Secret
          validation: required
        - $formkit: text
          name: region
          label: Region
          placeholder: 如不填写，则默认为"Auto"
          help: 若Region为Auto无法使用，才需要填写对应Region
        - $formkit: text
          name: location
          label: 上传目录
          placeholder: 如不填写，则默认上传到根目录
        - $formkit: select
          name: protocol
          label: 绑定域名协议
          options:
            - label: HTTPS
              value: https
            - label: HTTP
              value: http
          validation: required
        - $formkit: text
          name: domain
          label: 绑定域名（CDN域名）
          placeholder: 如不设置，那么将使用 Bucket + EndPoint 作为域名
          help: 协议头请在上方设置，此处无需以"http://"或"https://"开头，系统会自动拼接
