apiVersion: v1alpha1
kind: "Role"
metadata:
  name: role-template-s3os-link
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/dependencies: |
      [ "role-template-manage-attachments", "role-template-view-plugins" ]
    rbac.authorization.halo.run/module: "S3 Attachments Management"
    rbac.authorization.halo.run/display-name: "S3 Link"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:s3os:link"]
rules:
  - apiGroups: [ "s3os.halo.run" ]
    resources: [ "policies" ]
    resourceNames: [ "s3" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "s3os.halo.run" ]
    resources: [ "objects" ]
    verbs: [ "get", "list" ]
  - nonResourceURLs: ["/apis/s3os.halo.run/v1alpha1/attachments/link"]
    verbs: [ "create" ]
