/* tslint:disable */
/* eslint-disable */
/**
 * Halo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.18.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { Attachment } from '../models';
/**
 * S3UnlinkControllerApi - axios parameter creator
 * @export
 */
export const S3UnlinkControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unlink: async (name: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('unlink', 'name', name)
            const localVarPath = `/apis/s3os.halo.run/v1alpha1/attachments/{name}`
                .replace(`{${"name"}}`, encodeURIComponent(String(name)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * S3UnlinkControllerApi - functional programming interface
 * @export
 */
export const S3UnlinkControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = S3UnlinkControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async unlink(name: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Attachment>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.unlink(name, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['S3UnlinkControllerApi.unlink']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * S3UnlinkControllerApi - factory interface
 * @export
 */
export const S3UnlinkControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = S3UnlinkControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {S3UnlinkControllerApiUnlinkRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unlink(requestParameters: S3UnlinkControllerApiUnlinkRequest, options?: RawAxiosRequestConfig): AxiosPromise<Attachment> {
            return localVarFp.unlink(requestParameters.name, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for unlink operation in S3UnlinkControllerApi.
 * @export
 * @interface S3UnlinkControllerApiUnlinkRequest
 */
export interface S3UnlinkControllerApiUnlinkRequest {
    /**
     * 
     * @type {string}
     * @memberof S3UnlinkControllerApiUnlink
     */
    readonly name: string
}

/**
 * S3UnlinkControllerApi - object-oriented interface
 * @export
 * @class S3UnlinkControllerApi
 * @extends {BaseAPI}
 */
export class S3UnlinkControllerApi extends BaseAPI {
    /**
     * 
     * @param {S3UnlinkControllerApiUnlinkRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof S3UnlinkControllerApi
     */
    public unlink(requestParameters: S3UnlinkControllerApiUnlinkRequest, options?: RawAxiosRequestConfig) {
        return S3UnlinkControllerApiFp(this.configuration).unlink(requestParameters.name, options).then((request) => request(this.axios, this.basePath));
    }
}

