/* tslint:disable */
/* eslint-disable */
/**
 * Halo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.18.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LinkRequest
 */
export interface LinkRequest {
    /**
     * 
     * @type {string}
     * @memberof LinkRequest
     */
    'groupName'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof LinkRequest
     */
    'objectKeys'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof LinkRequest
     */
    'policyName'?: string;
}

