/* tslint:disable */
/* eslint-disable */
/**
 * Halo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.18.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ObjectVo
 */
export interface ObjectVo {
    /**
     * 
     * @type {string}
     * @memberof ObjectVo
     */
    'displayName'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ObjectVo
     */
    'isLinked'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ObjectVo
     */
    'key'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjectVo
     */
    'lastModified'?: string;
}

