/* tslint:disable */
/* eslint-disable */
/**
 * Halo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.18.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UrlSuffixItem } from './url-suffix-item';

/**
 * 
 * @export
 * @interface S3OsProperties
 */
export interface S3OsProperties {
    /**
     * 
     * @type {string}
     * @memberof S3OsProperties
     */
    'accessKey'?: string;
    /**
     * 
     * @type {string}
     * @memberof S3OsProperties
     */
    'accessSecret'?: string;
    /**
     * 
     * @type {string}
     * @memberof S3OsProperties
     */
    'bucket'?: string;
    /**
     * 
     * @type {string}
     * @memberof S3OsProperties
     */
    'customTemplate'?: string;
    /**
     * 
     * @type {string}
     * @memberof S3OsProperties
     */
    'domain'?: string;
    /**
     * 
     * @type {string}
     * @memberof S3OsProperties
     */
    'duplicateFilenameHandling'?: S3OsPropertiesDuplicateFilenameHandlingEnum;
    /**
     * 
     * @type {boolean}
     * @memberof S3OsProperties
     */
    'enablePathStyleAccess'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof S3OsProperties
     */
    'endpoint'?: string;
    /**
     * 
     * @type {string}
     * @memberof S3OsProperties
     */
    'endpointProtocol'?: S3OsPropertiesEndpointProtocolEnum;
    /**
     * 
     * @type {string}
     * @memberof S3OsProperties
     */
    'location'?: string;
    /**
     * 
     * @type {string}
     * @memberof S3OsProperties
     */
    'protocol'?: S3OsPropertiesProtocolEnum;
    /**
     * 
     * @type {string}
     * @memberof S3OsProperties
     */
    'randomFilenameMode'?: S3OsPropertiesRandomFilenameModeEnum;
    /**
     * 
     * @type {number}
     * @memberof S3OsProperties
     */
    'randomStringLength'?: number;
    /**
     * 
     * @type {string}
     * @memberof S3OsProperties
     */
    'region'?: string;
    /**
     * 
     * @type {Array<UrlSuffixItem>}
     * @memberof S3OsProperties
     */
    'urlSuffixes'?: Array<UrlSuffixItem>;
}

export const S3OsPropertiesDuplicateFilenameHandlingEnum = {
    RandomAlphanumeric: 'randomAlphanumeric',
    RandomAlphabetic: 'randomAlphabetic',
    Exception: 'exception'
} as const;

export type S3OsPropertiesDuplicateFilenameHandlingEnum = typeof S3OsPropertiesDuplicateFilenameHandlingEnum[keyof typeof S3OsPropertiesDuplicateFilenameHandlingEnum];
export const S3OsPropertiesEndpointProtocolEnum = {
    Http: 'http',
    Https: 'https'
} as const;

export type S3OsPropertiesEndpointProtocolEnum = typeof S3OsPropertiesEndpointProtocolEnum[keyof typeof S3OsPropertiesEndpointProtocolEnum];
export const S3OsPropertiesProtocolEnum = {
    Http: 'http',
    Https: 'https'
} as const;

export type S3OsPropertiesProtocolEnum = typeof S3OsPropertiesProtocolEnum[keyof typeof S3OsPropertiesProtocolEnum];
export const S3OsPropertiesRandomFilenameModeEnum = {
    None: 'none',
    Custom: 'custom',
    Uuid: 'uuid',
    TimestampMs: 'timestampMs',
    DateWithString: 'dateWithString',
    DatetimeWithString: 'datetimeWithString',
    WithString: 'withString',
    String: 'string',
    RandomNumber: 'random_number'
} as const;

export type S3OsPropertiesRandomFilenameModeEnum = typeof S3OsPropertiesRandomFilenameModeEnum[keyof typeof S3OsPropertiesRandomFilenameModeEnum];


