/* tslint:disable */
/* eslint-disable */
/**
 * Halo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.18.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UrlSuffixItem
 */
export interface UrlSuffixItem {
    /**
     * 
     * @type {string}
     * @memberof UrlSuffixItem
     */
    'fileSuffix'?: string;
    /**
     * 
     * @type {string}
     * @memberof UrlSuffixItem
     */
    'urlSuffix'?: string;
}

